AllCops:
  TargetRubyVersion: 2.6.3

Layout/LineLength:
  Max: 120

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 15

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Exclude:
    - config/application.rb

Style/EmptyLiteral:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
