version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.docker/development/Dockerfile
      args:
        RUBY_VERSION: '2.6.3'
        BUNDLER_VERSION: '2.0.2'
    image: cartafact-dev:0.1.0
    volumes:
      - .:/app:cached
      - rails_cache:/cartafact/tmp/cache
      - bundle:/bundle
      - node_modules_app:/cartafact/node_modules
      - packs:/cartafact/public/packs
    tmpfs:
      - /tmp
    command: bash -c "mkdir -p tmp/pids && bundle exec puma -C config/puma.rb"
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-27017}

    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-27017}
  db:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017

volumes:
  bundle:
  rails_cache:
  node_modules_app:
  packs:
  mongodb:
  mongodb_config:

